version: '3.3'
services:
  config-service:
    image: kanghonggoo/config-service
    ports:
      - "8888:8888"
    container_name: config-service
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.profiles.active=default
    networks:
      my-network:
  react: 
    image: kanghonggoo/negomarket
    ports:
      - "80:80"
    container_name: negomarket
    depends_on:
      - config-service
    networks:
      my-network:
        ipv4_address: 172.18.0.99
  apigateway-service:
    image: twojungho/apigateway-service
    ports:
      - "8000:8000"
    container_name: apigateway-service
    environment:
      - spring.rabbitmq.host=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8888
    depends_on:
      - config-service
    networks:
      my-network:
        ipv4_address: 172.18.0.98
  discovery-service:
    image: kanghonggoo/discovery-service
    ports:
      - "8761:8761"
    container_name: discovery-service
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.cloud.config.uri=http://config-service:8888
    depends_on:
      - config-service
    networks:
      my-network:
  user-service:
    image: kanghonggoo/user-service
    container_name: user-service
    environment:
      - spring.rabbitmq.host=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8888
      - spring.datasource.url=jdbc:mysql://mysql:3306/mydb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    depends_on:
      - config-service
    networks:
      my-network:
networks:
  my-network:
    external: 
      name: ecommerce-network